# Generated by Django 4.2.13 on 2024-05-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
