# Generated by Django 4.2.13 on 2024-05-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Kazakhstan', max_length=255, verbose_name='Country'),
        ),
    ]
