# Generated by Django 4.2.13 on 2024-05-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash',
        ),
    ]
