# Generated by Django 4.2.13 on 2024-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='voice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
