# Generated by Django 4.2.13 on 2024-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegrammessage_image_url_telegrammessage_voice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
