# Generated by Django 4.2.13 on 2024-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdate',
            name='update_id',
            field=models.IntegerField(default=0),
        ),
    ]
